name: ${NAME}
version: ${VERSION}
description: A plugin for plugin made by our
author: Akazukin-Team
authors: [ Currypan1229 ]
website: https://discord.gg/De8T2NS74X
softdepend:
  - WorldEdit
  - WorldGuard
  - FastAsyncWorldEdit
  - GrimAC

database: false

main: net.akazukin.library.LibraryPlugin
api-version: 1.19

load: STARTUP

commands:
  akazukin:
    description: Mapart command
    usage: /<command> help
